### ISSUE TITLE
Anycable integration

### ISSUE THREAD

**Issue by sebyx07** [raen79/fie#14]
If you could integrate with https://github.com/anycable/anycable-rails to offer good performance, this could turn into a Meteor like project

**Comment by raen79** [comment]
At the moment https://fie.eranpeer.co is running on anycable and ActionCable is only used for development. Essentially it is 100% compatible with it. I don't think it is necessary to actually include it into the project as anycable at the moment requires a lot of configuration (although I highly recommend using it). I do recommend using it throughout the website.
