### ISSUE TITLE
"Hello World" example in tutorial has incorrect paths

### ISSUE THREAD

**Issue by reassured-jy** [raen79/fie#15]
In the Hello World example at https://fie.eranpeer.co/start, the `hello_world_controller.rb` is in `app/commanders` and the `hello_world_commander.rb` is in `app_controllers`. These should be the other way around, shouldn't they?

(apologies if you didn't want documentation issues in GitHub — I wasn't sure of the correct place to put this)

**Comment by raen79** [comment]
The documentation has been updated accordingly so i am closing the issue.
