### ISSUE TITLE
Websocket Network Error in the showcase page

### ISSUE THREAD

**Issue by kirykr** [raen79/fie#16]
I tired to play around with the showcase. It does not work.

https://fie.eranpeer.co/showcase#todo

I inspected the browser console and here is the error:
```
WebSocket network error: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 2.)
```

**Comment by raen79** [comment]
Yes thank you i had just migrated the server to a new host and forgot to change the address for websockets. Just fixed it now!
