### ISSUE TITLE
Shrinking JavaScript code sizes?

### ISSUE THREAD

**Issue by nowhereman** [raen79/fie#18]
Hi Eran,

Your project looks <s>great</s> amazing, many thanks to open sourced your work!

By the way, the [`fie.js`](https://github.com/raen79/fie/blob/master/vendor/javascript/fie.js) file, even minified, is pretty big ~580 KB
Do you plan to reduce its size?
I guess the main reason is using [Opal](https://github.com/opal/opal)'s runtime.
And I understand that you prefer to code in Ruby rather than in another language :smile_cat:
> A deep burning desire to write less Javascript

But it would be great to get a `fie.js` below 100 KB, maybe in using just specific modules of Opal or switching to [CoffeeScript 2](https://github.com/jashkenas/coffeescript/wiki/CoffeeScript-2-Project) or even ECMAScript 2018/2019...

NB: Sorry for my English, I'm not a native speaker

Have a good day,
Nowhere Man

**Comment by raen79** [comment]
Hi Nowhere Man,

The file is indeed quite large, although only ~100kb when gzipped. I will try to use less Opal modules and see if it solves the problem.

Eran

**Comment by raen79** [comment]
https://github.com/raen79/fie/commit/26f981d325d76299c6d1b3da5b4fe2458ca9999b it is now ~50kb.

**Comment by nowhereman** [comment]
Wow impressive! Many thanks @raen79 :+1:
